// <auto-generated />
using System;
using DevicesApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevicesApi.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220928144501_Add_DeviceId_Migration")]
    partial class Add_DeviceId_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DevicesApi.Core.Entities.DeviceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("AdvancedEnvironmentalConditions")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeviceTypeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Failsafe")
                        .HasColumnType("bit");

                    b.Property<bool>("InsertInto19InchCabinet")
                        .HasColumnType("bit");

                    b.Property<int>("InstallationPosition")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MotionEnable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("PositionAxisNumber")
                        .HasColumnType("float");

                    b.Property<double>("RotationAxisNumber")
                        .HasColumnType("float");

                    b.Property<bool>("SimaticCatalog")
                        .HasColumnType("bit");

                    b.Property<bool>("SiplusCatalog")
                        .HasColumnType("bit");

                    b.Property<double>("TempMax")
                        .HasColumnType("float");

                    b.Property<double>("TempMin")
                        .HasColumnType("float");

                    b.Property<bool?>("TerminalElement")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("DeviceEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchivedAt = new DateTime(2022, 9, 28, 16, 45, 0, 611, DateTimeKind.Local).AddTicks(6263),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 45, 0, 609, DateTimeKind.Local).AddTicks(6335),
                            CreatedBy = "SYSTEM",
                            DeviceId = "9RLMugEpCVSeemZ5",
                            DeviceTypeId = "Beweis",
                            Failsafe = false,
                            InsertInto19InchCabinet = false,
                            InstallationPosition = 0,
                            ModifiedAt = new DateTime(2022, 9, 28, 16, 45, 0, 611, DateTimeKind.Local).AddTicks(6248),
                            ModifiedBy = "SYSTEM",
                            MotionEnable = true,
                            Name = "S7-150009",
                            PositionAxisNumber = 0.0,
                            RotationAxisNumber = 0.0,
                            SimaticCatalog = false,
                            SiplusCatalog = false,
                            TempMax = 60.0,
                            TempMin = 0.0
                        },
                        new
                        {
                            Id = 2,
                            AdvancedEnvironmentalConditions = false,
                            ArchivedAt = new DateTime(2022, 9, 28, 16, 45, 0, 611, DateTimeKind.Local).AddTicks(9981),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 45, 0, 611, DateTimeKind.Local).AddTicks(9968),
                            CreatedBy = "SYSTEM",
                            DeviceId = "1glmLrTZqf9YZleN",
                            DeviceTypeId = "S7_1500",
                            Failsafe = true,
                            InsertInto19InchCabinet = true,
                            InstallationPosition = 1,
                            ModifiedAt = new DateTime(2022, 9, 28, 16, 45, 0, 611, DateTimeKind.Local).AddTicks(9979),
                            ModifiedBy = "SYSTEM",
                            MotionEnable = true,
                            Name = "S7-1500",
                            PositionAxisNumber = 0.0,
                            RotationAxisNumber = 0.0,
                            SimaticCatalog = false,
                            SiplusCatalog = false,
                            TempMax = 50.0,
                            TempMin = 0.0
                        },
                        new
                        {
                            Id = 3,
                            AdvancedEnvironmentalConditions = false,
                            ArchivedAt = new DateTime(2022, 9, 28, 16, 45, 0, 612, DateTimeKind.Local).AddTicks(287),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 45, 0, 612, DateTimeKind.Local).AddTicks(278),
                            CreatedBy = "SYSTEM",
                            DeviceId = "9RLMugEbCVSeemZ4",
                            DeviceTypeId = "ET200_SP",
                            Failsafe = false,
                            InsertInto19InchCabinet = false,
                            InstallationPosition = 0,
                            ModifiedAt = new DateTime(2022, 9, 28, 16, 45, 0, 612, DateTimeKind.Local).AddTicks(286),
                            ModifiedBy = "SYSTEM",
                            MotionEnable = true,
                            Name = "ET 200SP",
                            PositionAxisNumber = 0.0,
                            RotationAxisNumber = 0.0,
                            SimaticCatalog = false,
                            SiplusCatalog = false,
                            TempMax = 40.0,
                            TempMin = 0.0,
                            TerminalElement = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
