// <auto-generated />
using DevicesApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;

#nullable disable

namespace DevicesApi.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DevicesApi.Core.Entities.RandomEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RandomEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArchivedAt = new DateTime(2021, 12, 5, 14, 33, 40, 418, DateTimeKind.Local).AddTicks(432),
                            CreatedAt = new DateTime(2021, 12, 5, 14, 33, 40, 416, DateTimeKind.Local).AddTicks(877),
                            CreatedBy = "SYSTEM",
                            Description = "None",
                            ModifiedAt = new DateTime(2021, 12, 5, 14, 33, 40, 418, DateTimeKind.Local).AddTicks(420),
                            ModifiedBy = "SYSTEM",
                            Name = "Random1"
                        },
                        new
                        {
                            Id = 2,
                            ArchivedAt = new DateTime(2021, 12, 5, 14, 33, 40, 418, DateTimeKind.Local).AddTicks(1569),
                            CreatedAt = new DateTime(2021, 12, 5, 14, 33, 40, 418, DateTimeKind.Local).AddTicks(1558),
                            CreatedBy = "SYSTEM",
                            Description = "None",
                            ModifiedAt = new DateTime(2021, 12, 5, 14, 33, 40, 418, DateTimeKind.Local).AddTicks(1567),
                            ModifiedBy = "SYSTEM",
                            Name = "Random2"
                        },
                        new
                        {
                            Id = 3,
                            ArchivedAt = new DateTime(2021, 12, 5, 14, 33, 40, 418, DateTimeKind.Local).AddTicks(1574),
                            CreatedAt = new DateTime(2021, 12, 5, 14, 33, 40, 418, DateTimeKind.Local).AddTicks(1572),
                            CreatedBy = "SYSTEM",
                            Description = "None",
                            ModifiedAt = new DateTime(2021, 12, 5, 14, 33, 40, 418, DateTimeKind.Local).AddTicks(1573),
                            ModifiedBy = "SYSTEM",
                            Name = "Random3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
